excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://digitalhitler.github.io
title: Sergey S Petrenko
tagline: A log of everyday life
description: My awesome new site
paginate: 10